### ISSUE TITLE
Generowanie planu powoduje błąd ERROR: Podane źródło jest nieprawidłowe

### ISSUE THREAD

**Issue by michalrud** [teamon/pwr#2]
Po dzisiejszych zapisach przy próbie generowania planu zajęć pojawia się błąd:

> ERROR: Podane źródło jest nieprawidłowe

Możliwe, że zmienili sposób wyświetlania, możliwe również, że w wyniku dzisiejszego NullPointerException Bonanza na Edukacji coś się pomieszało i wróci do normy dopiero za jakiś czas...

**Comment by teamon** [comment]
Wyslij mi na maila zrodlo to zobacze co jest nie tak (o ile sam sie zdarze zapisac dzisiaj ...)

**Comment by lpolitowski** [comment]
Na Operze wywala ten błąd przy wybraniu opcji iCal i VCS, reszta działa.

**Comment by michalrud** [comment]
Dodam, że przy drugiej próbie (pobrałem nowe źródło z EduCL) udało mi się wygenerować plan, więc to mogły być psikusy tegoż niezawodnego systemu

**Comment by teamon** [comment]
Podawajcie prosze zrodla bo bez tego nie mam jak sprawdzic co jest nie tak (moze byc na maila/gista, cokolwiek)

**Comment by Bonaducci** [comment]
Po kilku nieudanych próbach wysłałem Ci na maila mój kod źródłowy. Może coś w nim znajdziesz. Jeszcze popróbuję, ale nie znam do końca sposobu, w jaki kod jest parsowany, więc wiele raczej nie wymyślę.
